# Generated by Django 6.0 on 2025-12-17 08:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/category/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_address', models.TextField()),
                ('area', models.CharField(choices=[('Station Road', 'Station Road'), ('Main Market', 'Main Market'), ('Civil Lines', 'Civil Lines'), ('Shivrajpur', 'Shivrajpur')], default='Main Market', max_length=50)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('status', models.BooleanField(default=False, help_text='Tick karo agar Delivery ho gayi')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Khareed Rate (Profit nikalne ke liye)', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, help_text='Bechne ka Rate', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Kitne piece bache hain?')),
                ('image', models.ImageField(upload_to='uploads/product/')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('ltr', 'Liter'), ('pcs', 'Pieces'), ('pkt', 'Packet')], default='pcs', max_length=10)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
