# Generated by Django 5.2.9 on 2025-12-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_notification_alter_banner_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(choices=[('Delivery', 'Home Delivery'), ('Pickup', 'Self Pickup (Dukaan se lenge)')], default='Delivery', max_length=20),
        ),
    ]
