# Generated by Django 5.2.9 on 2025-12-31 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_user_alter_banner_id_alter_cart_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.IntegerField(default=0, help_text='Ab tak kitne bike'),
        ),
    ]
