# Generated by Django 5.2.9 on 2026-01-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_total_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.AddField(
            model_name='order',
            name='address_details',
            field=models.TextField(blank=True, help_text='House No, Gali No, Landmark'),
        ),
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.CharField(choices=[('mansarovar', 'Man Sarovar'), ('post_office_camp', 'Post Office Camp'), ('shubh_city', 'Shubh City'), ('chawala_chowk', 'Chawala Chowk'), ('shani_mandir_camp', 'Shani Mandir Camp'), ('hospital_line', 'Hospital Line'), ('adm_line', 'ADM Line'), ('gram_panchayat', 'Gram Panchayat'), ('bangla_line', 'Bangla Line'), ('audinance_factory', 'Audinance Factory'), ('keren_line', 'Keren Line'), ('samdariya_colony', 'Samdariya Colony'), ('mes', 'MES'), ('sabji_mandi_camp', 'Sabji Mandi Camp'), ('shanti_nagar', 'Shanti Nagar')], default='mansarovar', help_text='Area Select Karein', max_length=100),
        ),
    ]
