# Generated by Django 5.2.9 on 2026-02-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_customer_address_order_address_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.CharField(choices=[('madhavnagar', 'Madhav Nagar')], default='madhavnagar', help_text='Area Select Karein', max_length=100),
        ),
    ]
