# Generated by Django 5.2.9 on 2026-06-02 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_order_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_type',
            field=models.CharField(choices=[('weight', 'Weight / Size (Grocery ke liye)'), ('color', 'Color / Rang (Crockery/Jug ke liye)')], default='weight', help_text='Customer ko kya dikhana hai: Gram/Ltr ya Color?', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_or_size', models.CharField(blank=True, help_text='e.g. 100g, 200g, 1Ltr (Grocery ke liye)', max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text='e.g. Red, Black, Green (Crockery ke liye)', max_length=50, null=True)),
                ('market_price', models.DecimalField(decimal_places=2, default=0, help_text='MRP', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, help_text='Bechne ka Rate', max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Khareed Rate', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0, help_text='Stock me kitna hai')),
                ('total_sold', models.IntegerField(default=0, help_text='Kitne bike')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
        ),
    ]
