# Generated by Django 5.2.9 on 2026-06-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cartitem_variant_orderitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/variants/'),
        ),
    ]
