# Generated by Django 5.2.9 on 2026-09-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productvariant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Area Zone Name (e.g. Ameerganj Zone)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('coordinates', models.TextField(default='[]', help_text='JSON format me Leaflet.js polygon coordinates')),
            ],
        ),
    ]
